export const tags = [
  "Atmospheric",
  "Fantasy",
  "Relaxing",
  "Funny",
  "Sci-fi",
  "Horror",
  "Family Friendly",
  "Retro",
  "Survival",
  "Comedy",
  "Mystery",
  "Dark",
  "Sports",
  "️Old School",
  "Psychological Horror",
  "Medieval",
  "Racing",
  "Magic",
  "Space",
  "Building",
  "Tactical",
  "Management",
  "Futuristic",
  "Drama",
  "Logic",
  "Crafting",
  "Romance",
  "Dark Fantasy",
  "Survival Horror",
  "Emotional",
  "1980s",
  "Education",
  "Nature",
  "1990's",
  "️Post-apocalyptic",
  "Surreal",
  "️War",
  "Zombies",
  "Historical",
  "Stealth",
  "Investigation",
  "Military",
  "️‍LGBTQ+",
  "Cyberpunk",
  "Robots",
  "️Detective",
  "Aliens",
  "Lore-Rich",
  "Economy",
  "Dark Humor",
  "Demons",
  "Thriller",
  "Driving",
  "Psychological",
  "Supernatural",
  "Modern",
  "Comic Book",
  "Psychedelic",
  "️Flight",
  "Memes",
  "Dystopian",
  "Artificial Intelligence",
  "Loot",
  "️Alternate History",
  "Parkour",
  "Mythology",
  "Cats",
  "Destruction",
  "Crime",
  "️Game Development",
  "‍Philosophical",
  "Dark Comedy",
  "Capitalism",
  "Automation",
  "Science",
  "Lovecraftian",
  "Swordplay",
  "️Noir",
  "Dragons",
  "World War II",
  "America",
  "Cooking",
  "Parody",
  "Agriculture",
  "️Conspiracy",
  "Martial Arts",
  "Mechs",
  "Gothic",
  "‍Pirates",
  "Satire",
  "️Underground",
  "Steampunk",
  "Dog",
  "Time Travel",
  "️Mining",
  "Tanks",
  "️Political",
  "Ninja",
  "Hunting",
  "Underwater",
  "Otome",
  "Vampire",
  "Fishing",
  "Dinosaurs",
  "Transportation",
  "Hacking",
  "Western",
  "Programming",
  "Superhero",
  "Faith",
  "Trains",
  "️Assassin",
  "️Politics",
  "Gambling",
  "Naval",
  "Diplomacy",
  "Heist",
  "Archery",
  "️Cold War",
  "️Snow",
  "Sailing",
  "Football (Soccer)",
  "Offroad",
  "Horses",
  "Foreign",
  "️Illuminati",
  "Sniper",
  "Transhumanism",
  "Mars",
  "Boxing",
  "️Jet",
  "Werewolves",
  "️Motorbike",
  "️Golf",
  "Bikes",
  "️World War I",
  "️Rome",
  "Submarine",
  "Basketball",
  "LEGO",
  "Skateboarding",
  "Mini Golf",
  "Wrestling",
  "Football (American)",
  "Tennis",
  "Pool",
  "Baseball",
  "Cycling",
  "Skating",
  "Warhammer 40K",
  "Motocross",
  "Lemmings",
  "Hockey",
  "Bowling",
  "Skiing",
  "Snowboarding",
  "BMX",
  "ATV",
  "Indie",
  "Action",
  "Casual",
  "️Adventure",
  "️Simulation",
  "RPG",
  "Strategy",
  "Action-Adventure",
  "Software",
  "2D",
  "3D",
  "Colorful",
  "Pixel Graphics",
  "Cute",
  "First-Person",
  "Anime",
  "Third Person",
  "Stylized",
  "️Top-Down",
  "Realistic",
  "Cartoony",
  "Minimalist",
  "Hand-drawn",
  "VR",
  "Cartoon",
  "Text-Based",
  "Cinematic",
  "2.5D",
  "Isometric",
  "Abstract",
  "Split Screen",
  "3D Vision",
  "Beautiful",
  "Voxel",
  "FMV",
  "360 Video",
  "Story Rich",
  "️Combat",
  "Female Protagonist",
  "Controller",
  "Open World",
  "Choices Matter",
  "PvP",
  "Linear",
  "PvE",
  "Multiple Endings",
  "Physics",
  "Character Customization",
  "Procedural Generation",
  "Tabletop",
  "️Turn-Based Combat",
  "Turn-Based Tactics",
  "️Hack and Slash",
  "Resource Management",
  "Base Building",
  "Score Attack",
  "Narration",
  "️Conversation",
  "〰️Nonlinear",
  "️Perma Death",
  "Team-Based",
  "Tutorial",
  "Deckbuilding",
  "Inventory Management",
  "Level Editor",
  "️Grid-Based Movement",
  "️Moddable",
  "️Class-Based",
  "️Vehicular Combat",
  "Gun Customization",
  "6DOF",
  "️Bullet Time",
  "Trading",
  "Time Manipulation",
  "Quick-Time Events",
  "Dynamic Narration",
  "Hex Grid",
  "Naval Combat",
  "Music-Based Procedural Generation",
  "Asymmetric VR",
  "Puzzle",
  "Arcade",
  "Shooter",
  "️Platformer",
  "Visual Novel",
  "Sandbox",
  "Action RPG",
  "Point & Click",
  "Rogue-like",
  "Action Roguelike",
  "Turn-Based Strategy",
  "Interactive Fiction",
  "Party-Based RPG",
  "JRPG",
  "Dating Sim",
  "Design & Illustration",
  "Walking Simulator",
  "Card Game",
  "Life Sim",
  "Utilities",
  "Strategy RPG",
  "RTS",
  "Board Game",
  "Tower Defense",
  "Web Publishing",
  "️City Builder",
  "Beat 'em up",
  "2D Fighter",
  "Automobile Sim",
  "Rhythm",
  "3D Fighter",
  "Animation & Modeling",
  "Farming Sim",
  "️Grand Strategy",
  "Space Sim",
  "Colony Sim",
  "eSports",
  "MMORPG",
  "️Battle Royale",
  "Word Game",
  "Auto Battler",
  "Audio Production",
  "Video Production",
  "God Game",
  "️4X",
  "MOBA",
  "Photo Editing",
  "Trivia",
  "Immersive Sim",
  "🪖Military",
  "🪂World War II",
  "️Political Sim",
  "Outbreak Sim",
  "Medical Sim",
  "Short",
  "Movie",
  "Episodic",
  "Documentary",
  "Gaming",
  "Exploration",
  "2D Platformer",
  "FPS",
  "Rogue-lite",
  "Shoot 'Em Up",
  "Side Scroller",
  "3D Platformer",
  "Choose Your Own Adventure",
  "Puzzle-Platformer",
  "Hidden Object",
  "Bullet Hell",
  "Dungeon Crawler",
  "Top-Down Shooter",
  "Clicker",
  "Third-Person Shooter",
  "Precision Platformer",
  "️Real Time Tactics",
  "Arena Shooter",
  "Time Management",
  "Collectathon",
  "️Tactical RPG",
  "Wargame",
  "Metroidvania",
  "Idler",
  "Runner",
  "Souls-like",
  "Card Battler",
  "CRPG",
  "️Twin Stick Shooter",
  "Creature Collector",
  "3️Match 3",
  "Mystery Dungeon",
  "Hero Shooter",
  "️Combat Racing",
  "Spectacle fighter",
  "Looter Shooter",
  "️Solitaire",
  "Action RTS",
  "Sokoban",
  "Trading Card Game",
  "️Typing",
  "Traditional Roguelike",
  "Boomer Shooter",
  "️On-Rails Shooter",
  "Spelling",
  "Roguevania",
  "Singleplayer",
  "️Multiplayer",
  "Co-op",
  "Online Co-Op",
  "🫶Massively Multiplayer",
  "Local Multiplayer",
  "Local Co-Op",
  "4️4 Player Local",
  "Co-op Campaign",
  "Asynchronous Multiplayer",
  "Profile Features Limited",
  "Demo Available",
  "Fighting",
  "Classic",
  "️Cozy",
  "Open World Survival Craft",
  "Wholesome",
  "Roguelike Deckbuilder",
  "Narrative",
  "Immersive",
  "Party Game",
  "Party",
  "️Escape Room",
  "🫦Addictive",
  "Cult Classic",
  "️Nostalgia",
  "Farming",
  "Electronic Music",
  "🠊Social Deduction",
  "Spaceships",
  "Ambient",
  "Dwarf",
  "Pinball",
  "Epic",
  "Job Simulator",
  "Instrumental Music",
  "Jump Scare",
  "️Tile-Matching",
  "Rock Music",
  "Boss Rush",
  "Vikings",
  "8-bit Music",
  "Extraction Shooter",
  "Mahjong",
  "️Well-Written",
  "Electronic",
  "️Shop Keeper",
  "Birds",
  "Musou",
  "Fox",
  "Elf",
  "Coding",
  "Hobby Sim",
  "Cricket",
  "Rugby",
  "Volleyball",
  "Snooker",
  "Reboot",
  "Based On A Novel",
  "Free to Play",
  "Early Access",
  "️Experimental",
  "Software Training",
  "Minigames",
  "Remake",
  "2️Sequel",
  "Experience",
  "Kickstarter",
  "Crowdfunded",
  "Benchmark",
  "Feature Film",
  "Difficult",
  "Competitive",
  "Unforgiving",
  "Turn-Based",
  "Replay Value",
  "Fast-Paced",
  "🤏Short",
  "️Real-Time",
  "Time Attack",
  "Real-Time with Pause",
  "Sexual Content",
  "Nudity",
  "Mature",
  "🫣NSFW",
  "Character Action Game",
  "Villain Protagonist",
  "Silent Protagonist",
  "Violent",
  "Gore",
  "Blood",
  "️Chess",
  "Soundtrack",
  "Great Soundtrack",
  "Music",
  "️Mouse only",
  "Touch-Friendly",
  "Intentionally Awkward Controls",
  "️Voice Control",
  "Mod",
  "RPGMaker",
  "GameMaker",
  "Dungeons & Dragons",
  "️Games Workshop",
  "TrackIR",
  "Hardware",
  "Steam Machine",
].map((t) => ({
  label: t,
  value: t,
}));
